import { strict as assert } from 'node:assert'; import fs from 'node:fs/promises';
import { jobsForMerge,spawnRemediation,spawnJustInTimeReview } from './WorkEvidenceScheduler.ts';
import { runnable,upsertJob,loadLedger,saveLedger,type LabLedger } from './LabJobLedger.ts';
const jobs=jobsForMerge({specimenSha:'825da88d1529486c8e7891825b9faa1946412c21',sourcePr:772,mergedAt:'2026-09-19T00:00:00Z'});
assert.deepEqual(jobs.map(j=>j.kind),['deterministic','xr-simulation','quest-automation']); assert(jobs.every(j=>j.specimenSha.startsWith('825da88d')));
let ledger:LabLedger={version:1,jobs:[]}; for(const j of jobs)ledger=upsertJob(ledger,j); assert.equal(runnable(ledger).length,3);
jobs[1]!.status='FINDING'; const fix=spawnRemediation(jobs[1]!); assert.equal(fix.dependsOn[0],jobs[1]!.id); assert.equal(jobs[1]!.successorIds[0],fix.id);
const review=spawnJustInTimeReview(jobs[1]!,['xr-lifecycle']); assert.equal(review.kind,'adversarial-review'); assert.equal(review.specimenSha,jobs[1]!.specimenSha);
const path='.scheduler-selftest.json'; await saveLedger(path,ledger); assert.equal((await loadLedger(path)).jobs.length,3); await fs.unlink(path);
console.log('scheduler self-test: PASS');
