import { strict as assert } from 'node:assert';
import { execFileSync } from 'node:child_process';
import fs from 'node:fs/promises';
import path from 'node:path';
import { executeNativeJob } from './NativeWorkerAdapters.ts';
import type { LabJob } from './WorkProtocol.ts';

const root='.native-adapter-selftest';
const source=path.resolve(root,'nemosyne');
process.env.NEMOSYNE_LAB_EVIDENCE_ROOT=root;
process.env.NEMOSYNE_SOURCE_ROOT=source;
delete process.env.NEMOSYNE_PERTURBATION_CONFIG;
await fs.rm(root,{recursive:true,force:true});
await fs.mkdir(path.join(source,'node_modules','vitest'),{recursive:true});
await fs.mkdir(path.join(source,'tests'),{recursive:true});
await fs.mkdir(path.join(source,'scripts'),{recursive:true});
await fs.writeFile(path.join(source,'node_modules','vitest','vitest.mjs'),"process.stdout.write('fake native suite pass\\n');\n");
await fs.writeFile(path.join(source,'scripts','build-wasm.mjs'),"process.stdout.write('fake wasm build pass\\n');\n");
await fs.writeFile(path.join(source,'vitest.config.ts'),'// fixture\n');
await fs.writeFile(path.join(source,'vitest.wasm.config.ts'),'// fixture\n');
for(const name of ['moneta-known-structure-campaign-wasm','representation-resource-lifecycle','resource-lifecycle-governor']){
  await fs.writeFile(path.join(source,'tests',name+'.test.ts'),'// fixture\n');
}
await fs.writeFile(path.join(source,'fixture.txt'),'fixture\n');
execFileSync('git',['init','-q'],{cwd:source});
execFileSync('git',['config','user.email','lab-selftest@nemosyne.invalid'],{cwd:source});
execFileSync('git',['config','user.name','Nemosyne Lab Selftest'],{cwd:source});
execFileSync('git',['add','.'],{cwd:source});
execFileSync('git',['commit','-qm','fixture'],{cwd:source});
const sha=execFileSync('git',['rev-parse','HEAD'],{cwd:source,encoding:'utf8'}).trim();
const mk=(worker:LabJob['worker'],specimenSha=sha,claims=['test']):LabJob=>({jobId:'test-'+worker+'-'+claims.join('-'),specimenSha,stream:worker==='xr-simulator'?'VSL':'RFL',worker,claims,state:'RUNNING',createdAt:new Date().toISOString(),evidenceRefs:[]});
const xr=await executeNativeJob(mk('xr-simulator'));
assert.equal(xr.disposition,'PASS');
assert.equal(xr.evidenceRefs.length,2);
const mismatch=await executeNativeJob(mk('xr-simulator','825da88d1529486c8e7891825b9faa1946412c21'));
assert.equal(mismatch.disposition,'ABSTAIN');
const perturbation=await executeNativeJob(mk('perturbation-campaign',sha,['semantic-preservation','bounded-runtime-resources']));
assert.equal(perturbation.disposition,'PASS');
assert.equal(perturbation.evidenceRefs.length,2);
const unsupported=await executeNativeJob(mk('perturbation-campaign',sha,['human-qualification']));
assert.equal(unsupported.disposition,'ABSTAIN');
const known=await executeNativeJob(mk('known-structure'));
assert.equal(known.disposition,'RECORDED');
assert.equal(known.evidenceRefs.length,1);
const body=JSON.parse(await fs.readFile(known.evidenceRefs[0]!,'utf8'));
assert.equal(body.specimenSha,sha);
await fs.rm(root,{recursive:true,force:true});
console.log('native worker adapter self-test: PASS');
